### ISSUE TITLE
grad transform failing tests tracking issue

### ISSUE THREAD

**Issue by zou3519** [zou3519/functorch#42]
Current fails for:
- [ ] __getitem__
- [ ] __rpow__
- [ ] float_power
- [ ] index_put
- [ ] linalg.cholesky
- [ ] linalg.inv
- [ ] linalg.matrix_norm
- [ ] linalg.matrix_power
- [ ] linalg.norm
- [ ] nanquantile
- [ ] pow
- [ ] einsum (cuda only)
- [ ] linalg.multi_dot (cuda only)
- [ ] quantile (cuda only)

Test by uncommenting out https://github.com/zou3519/functorch/blob/ae97def8eb8508418053a1a7c81371b9b44dcc3d/test/test_grad.py#L49. I haven't investigated the problems yet.

**Comment by zou3519** [comment]
internal_new_from_data: allowing data_ptr access for TensorWrapper that doesn't wrap BatchedTensor sounds fine
